export const INITIAL_LIMIT = 8;
export const SHIPPING_COST = 2000;
export const AMOUNT_FREE_SHIPPING = 15000;
export const REG_EMAIL = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;
export const BASE_URL = 'http://localhost:8080';
export const AVAILABLE_ZONES_DISPLAY = [
    { label: "Vicente López", value: "VICENTE_LOPEZ" },
    { label: "San Isidro", value: "SAN_ISIDRO" },
    { label: "San Fernando", value: "SAN_FERNANDO" },
    { label: "Tigre", value: "TIGRE" },
    { label: "Escobar", value: "ESCOBAR" },
    { label: "Pilar", value: "PILAR" },
    { label: "José C. Paz", value: "JOSE_C_PAZ" },
    { label: "Malvinas Argentinas", value: "MALVINAS_ARGENTINAS" },
    { label: "San Miguel", value: "SAN_MIGUEL" },
    { label: "San Martín", value: "SAN_MARTIN" },

    { label: "La Matanza", value: "LA_MATANZA" },
    { label: "Tres de Febrero", value: "TRES_DE_FEBRERO" },
    { label: "Hurlingham", value: "HURLINGHAM" },
    { label: "Morón", value: "MORON" },
    { label: "Ituzaingó", value: "ITUZAINGO" },
    { label: "Merlo", value: "MERLO" },
    { label: "Moreno", value: "MORENO" },
    { label: "General Rodríguez", value: "GENERAL_RODRIGUEZ" },
    { label: "Marcos Paz", value: "MARCOS_PAZ" },

    { label: "Avellaneda", value: "AVELLANEDA" },
    { label: "Lanús", value: "LANUS" },
    { label: "Lomas de Zamora", value: "LOMAS_DE_ZAMORA" },
    { label: "Esteban de Echeverría", value: "ESTEBAN_DE_ECHEVERRIA" },
    { label: "Ezeiza", value: "EZEIZA" },
    { label: "San Vicente", value: "SAN_VICENTE" },
    { label: "Presidente Perón", value: "PRESIDENTE_PERON" },
    { label: "Almirante Brown", value: "ALMIRANTE_BROWN" },
    { label: "Quilmes", value: "QUILMES" },
    { label: "Berazategui", value: "BERAZATEGUI" },
    { label: "Florencio Varela", value: "FLORENCIO_VARELA" },

    { label: "Agronomía", value: "AGRONOMIA" },
    { label: "Almagro", value: "ALMAGRO" },
    { label: "Balvanera", value: "BALVANERA" },
    { label: "Barracas", value: "BARRACAS" },
    { label: "Belgrano", value: "BELGRANO" },
    { label: "Boedo", value: "BOEDO" },
    { label: "Caballito", value: "CABALLITO" },
    { label: "Chacarita", value: "CHACARITA" },
    { label: "Coghlan", value: "COGHLAN" },
    { label: "Colegiales", value: "COLEGIALES" },
    { label: "Constitución", value: "CONSTITUCION" },
    { label: "Flores", value: "FLORES" },
    { label: "Floresta", value: "FLORESTA" },
    { label: "La Boca", value: "LA_BOCA" },
    { label: "La Paternal", value: "LA_PATERNAL" },
    { label: "Liniers", value: "LINIERS" },
    { label: "Mataderos", value: "MATADEROS" },
    { label: "Monte Castro", value: "MONTE_CASTRO" },
    { label: "Monserrat", value: "MONSERRAT" },
    { label: "Nueva Pompeya", value: "NUEVA_POMPEYA" },
    { label: "Núñez", value: "NUNEZ" },
    { label: "Palermo", value: "PALERMO" },
    { label: "Parque Avellaneda", value: "PARQUE_AVELLANEDA" },
    { label: "Parque Chacabuco", value: "PARQUE_CHACABUCO" },
    { label: "Parque Chas", value: "PARQUE_CHAS" },
    { label: "Parque Patricios", value: "PARQUE_PATRICIOS" },
    { label: "Puerto Madero", value: "PUERTO_MADERO" },
    { label: "Recoleta", value: "RECOLETA" },
    { label: "Retiro", value: "RETIRO" },
    { label: "Saavedra", value: "SAAVEDRA" },
    { label: "San Cristóbal", value: "SAN_CRISTOBAL" },
    { label: "San Nicolás", value: "SAN_NICOLAS" },
    { label: "San Telmo", value: "SAN_TELMO" },
    { label: "Vélez Sársfield", value: "VELEZ_SARSFIELD" },
    { label: "Versalles", value: "VERSALLES" },
    { label: "Villa Crespo", value: "VILLA_CRESPO" },
    { label: "Villa del Parque", value: "VILLA_DEL_PARQUE" },
    { label: "Villa Devoto", value: "VILLA_DEVOTO" },
    { label: "Villa General Mitre", value: "VILLA_GENERAL_MITRE" }
];



